export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESSFUL";
export const GET_LIST_FAIL = "GET_LIST_FAIL";
export const GET_LIST_CLEAR = "GET_LIST_CLEAR";

export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const UPDATE_LIST_FAIL = "UPDATE_LIST_FAIL";
